[package]
name = "day_2"
version = "0.1.0"
authors = ["Branden Vennes <b.n.vennes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util/rust" }
